# Generated by Django 4.2.7 on 2023-11-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20211129_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default/user.png', null=True, upload_to='profile_images'),
        ),
    ]
